name: Android Release Build

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.1'
          cache: true

      - name: Decode Keystore
        uses: timheuer/base64-to-file@v1.2
        id: android_keystore
        with:
          fileName: 'release.jks'
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

      - name: Move Keystore
        run: mv ${{ steps.android_keystore.outputs.filePath }} android/app/release.jks

      - name: Create key.properties
        env:
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        run: |
          echo "storePassword=$STORE_PASSWORD" > android/key.properties
          echo "keyPassword=$KEY_PASSWORD" >> android/key.properties
          echo "keyAlias=$KEY_ALIAS" >> android/key.properties
          echo "storeFile=release.jks" >> android/key.properties

      - name: Create .env
        env:
          API_BASE_URL: ${{ secrets.PROD_API_BASE_URL }}
          SUPABASE_URL: ${{ secrets.PROD_SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.PROD_SUPABASE_ANON_KEY }}
        run: |
          echo "API_BASE_URL=$API_BASE_URL" > .env
          echo "SUPABASE_URL=$SUPABASE_URL" >> .env
          echo "SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY" >> .env

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (Release)
        run: flutter build apk --release

      - name: Build App Bundle (AAB)
        run: flutter build appbundle --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: devpulse-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: devpulse-release-aab
          path: build/app/outputs/bundle/release/app-release.aab
